channels:
  - conda-forge
  - bioconda
dependencies:
  - perl >=5.32
  - perl-list-moreutils
  - perl-path-tiny
  - csvtk
  - seqkit
  - kmc
  - jellyfish
  - mercat2
  - sourmash
  - kmc
  - make
  - bats-core
